export const items =  [
    //    laptops 
        {
          id: 1,
          category: 'laptops',
          title: "Xiaomi [Smartchoice] Notebookpro",
          img1: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
          img2: 'https://m.media-amazon.com/images/I/61atYCE26YL._SY355_.jpg',
          img3: 'https://m.media-amazon.com/images/I/71G4myYJuAL._SY355_.jpg',
          img4: 'https://m.media-amazon.com/images/I/51cXOUpfQyL._SY355_.jpg',
          amazonLink: 'https://amzn.to/3EzeQaC',
          description: 'Xiaomi [Smartchoice] Notebookpro ',
          price: '49,999',
          rating: 5,
    
        },
         
      {
        id: 2,
        category: 'laptops',
        title: "Gamepad Controller",
        img1: "https://m.media-amazon.com/images/I/311RxBAWGCL._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/71VRHoEQyqL._SX466_.jpg",
        img3: "https://m.media-amazon.com/images/I/61NLOjxdLaL._SX466_.jpg",
        img4: "https://m.media-amazon.com/images/I/61Zw2fAGi0L._SX466_.jpg",
        description: 'EvoFox Elite X Wireless Gamepad for PC with Dual Vibration  pc (Red)',
        price: "249",
        rating: 4,
    },
        {
            id: 3,
            category: 'laptops',
            title: "Apple MacBook Air Laptop",
            img1: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
            img2: "https://m.media-amazon.com/images/I/91KREQM8C6L._SX522_.jpg",
            img3: "https://m.media-amazon.com/images/I/6155Fp7yaSL._SX522_.jpg",
            img4: "https://m.media-amazon.com/images/I/6155Fp7yaSL._SX522_.jpg",
            amazonLink: 'https://amzn.to/3r9rvhm',
            description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
            price: '89,999',
            rating: 4,
          },
          {
            id: 4,
            category: 'laptops',
            title: "MSI Bravo 15 AMD Ryzen 5 Hexa",
            img1: "https://m.media-amazon.com/images/I/71kEsKWBc2L._SX522_.jpg",
            img3: "https://m.media-amazon.com/images/I/616uBaa3urL._SY450_.jpg",
            img4: "https://m.media-amazon.com/images/I/711cHT5XIhL._SY450_.jpg",
            amazonLink: 'https://amzn.to/3PuckZp',
            description: 'MSI Bravo 15 AMD Ryzen 5 Hexa Core 7535HS - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/AMD Radeon RX6550M/144 Hz) Bravo 15 B7ED-012IN Gaming Laptop ',
            price: "45,990",
            rating: 4,
      
      
        },
        {
            id: 5,
            category: 'laptops',
            title: "ASUS ROG Strix G16 (2023)",
            img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/n/2/n/-original-imagqfxrg76yafrr.jpeg?q=70&crop=false",
            img2: "https://m.media-amazon.com/images/I/512MFfi514L._SY450_.jpg",
            img3: "https://m.media-amazon.com/images/I/81kD2g61U2L._SY450_.jpg",
            img4: "https://m.media-amazon.com/images/I/81y8EZ5uqVL._SY450_.jpg",
            amazonLink: 'https://amzn.to/3PuckZp',
            description: 'ASUS ROG Strix G16 (2023), Intel Intel Core i5 13th Gen 13450HX - (16 GB/1 TB SSD/Windows 11 Home/6 GB Graphics/NVIDIA GeForce RTX 3050) G614JJ-N3088WS Gaming Laptop  (16 Inch, Gray, 2.50 Kg, With MS Office)',
            price: "99,990",
            rating: 4,
          },
          {
            id: 6,
            category: 'laptops',
            title: "Ant Esports ICE- 112 Support ATX,",
            img1: "https://m.media-amazon.com/images/I/81seDgXX9vL._SY450_.jpg",
            img2: "https://m.media-amazon.com/images/I/81xq1lKxEeL._SY450_.jpg",
            img3: "https://m.media-amazon.com/images/I/71yWqmTxjSL._SY450_.jpg",
            img4: "https://m.media-amazon.com/images/I/61qhpiAvKeL._SY450_.jpg",
            amazonLink: '',
            description: 'Ant Esports ICE- 112 Support ATX, Micro-ATX, ITX | Pre-Installed 3 Front Fans & 1 Rear Fan Mid- Tower Computer Case/Gaming Cabinet  (Black)',
            price: "3,090",
            rating: 4,
      
      
        },
        {
            id: 7,
            category: 'laptops ',
            title: "ASUS TUF Gaming F15 - AI Powered Gaming",
            img1: "https://m.media-amazon.com/images/I/81x9vxrPFwS._SY450_.jpg",
            img2: "https://m.media-amazon.com/images/I/81x9vxrPFwS._SY450_.jpg",
            img3: "https://m.media-amazon.com/images/I/71dPTjiAwWL._SY450_.jpg",
            img4: "https://m.media-amazon.com/images/I/61WbJrVCbpL._SY450_.jpg",
            amazonLink: 'https://amzn.to/3PuckZp',
            description: 'ASUS TUF Gaming F15 - AI Powered Gaming Intel Core i5 11th Gen 11260H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 2050/144 Hz/70 TGP) FX506HF-HN075W Gaming Laptop  (15.6 Inch, Graphite Black, 2.30 kg)',
            price: "53,990",
            rating: 4,
    
    
        },
        {
            id: 8,
            category: 'laptops',
            title: "Lenovo IdeaPad Slim 5 ",
            img1: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
            img2: "https://m.media-amazon.com/images/I/51P2o0-bQGL._SY450_.jpg",
            img3: "https://m.media-amazon.com/images/I/61-BVUAst8L._SY450_.jpg",
            img4: "https://m.media-amazon.com/images/I/61kpqFi9TeL._SY450_.jpg",
            amazonLink: 'https://amzn.to/44JsK4r',
            description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
            price: '29,999',
            rating: 4,
          },
    
          {
            id: 9,
            category: 'laptops',
            title: "MSI Bravo 15 Gaming Laptop,AMD Ryzen 5 7535HS, 40CM FHD 144Hz Laptop",
            img1: "https://m.media-amazon.com/images/I/61PrdKgYaYL._SY450_.jpg",
            img2: "https://m.media-amazon.com/images/I/61F8lbn1LNL._SY450_.jpg",
            img3: "https://m.media-amazon.com/images/I/616uBaa3urL._SY450_.jpg",
            img4: "https://m.media-amazon.com/images/I/61ZYMkmCM8L._SY450_.jpg",
            description: 'MSI Bravo 15 Gaming Laptop,AMD Ryzen 5 7535HS, 40CM FHD 144Hz Laptop (8GB/512GB NVMe SSD/Windows 11 Home/Nvidia GeForce RTX 2050, GDDR6 4GB/Black/2.25Kg), C7UCXK-095IN',
            price: "249",
            rating: 4,
        },
        
    
    
    // tablets 
    
        {
          id: 10,
          category: 'tablets',
          title: "Xiaomi Pad 6",
          img1: "https://m.media-amazon.com/images/I/415gV21fNCL._SX300_SY300_QL70_FMwebp_.jpg",
          img2: "https://m.media-amazon.com/images/I/51wMVRxiDpL._SY355_.jpg",
          img3: "https://m.media-amazon.com/images/I/717-z0kLtML._SY355_.jpg",
          img4: "https://m.media-amazon.com/images/I/7135E0xd7xL._SY355_.jpg",
          amazonLink: 'https://amzn.to/3ZeNRdY',
          description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
          price: '29,999',
          rating: 4,
        },
    
        {
          id: 11,
          category: 'tablets',
          title: "Lenovo Tab P12 Pro AMOLED",
          img1: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
          img2: "https://m.media-amazon.com/images/I/61tlHIRr-aL._SY355_.jpg",
          img3: "https://m.media-amazon.com/images/I/61gnQV8o4vL._SY355_.jpg",
          img4: "https://m.media-amazon.com/images/I/51HxkNm+8nL._SY355_.jpg",
          amazonLink: 'https://amzn.to/3RabsdH',
          description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
          price: '19,999',
          rating: 4,
        },
       
      
        {
          id: 12,
          category: 'tablets',
          title: "Samsung Galaxy Tab A8",
          img1: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
          img2: "https://m.media-amazon.com/images/I/91TsHQKuxTL._SX450_.jpg",
          img3: "https://m.media-amazon.com/images/I/81hK40afBZL._SX450_.jpg",
          img4: "https://m.media-amazon.com/images/I/81f0sLb-foL._SX450_.jpg",
          amazonLink: 'https://amzn.to/3Pdsh4F',
          description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
          price: '49,999',
          rating: 4,
        },
    
        {
            id: 13,
            category: 'lablets',
            title: "Apple iPad (10th Generation): with A14 Bionic chip, 27.69 cm (10.9″)",
            img1: "https://m.media-amazon.com/images/I/31qx8K0wm+L._SX342_SY445_.jpg",
            img2: "https://m.media-amazon.com/images/I/91psKPUkS4L._SX466_.jpg",
            img3: "https://m.media-amazon.com/images/I/71Xe1DNqYgL._SX466_.jpg",
            img4: "https://m.media-amazon.com/images/I/A1pkJbeLMBL._SX466_.jpg",
            description: "Apple iPad (10th Generation): with A14 Bionic chip, 27.69 cm (10.9″) Liquid Retina Display, 256GB, Wi-Fi 6, 12MP front/12MP Back Camera, Touch ID, All-Day Battery Life – Blue",
            price: "51,900",
            rating: 4,
        },
    
        {
            id: 14,
            category: 'lablets',
            title: "Apple 2021 10.2-inch (25.91 cm) iPad with A13 Bionic chip (Wi-Fi + Cellular, 64GB)",
            img1: "https://m.media-amazon.com/images/I/31EEceRfixL._SY445_SX342_QL70_FMwebp_.jpg",
            img2: "https://m.media-amazon.com/images/I/61dBM-taNhL._SX466_.jpg",
            img3: "https://m.media-amazon.com/images/I/816hSwqPncL._SX466_.jpg",
            img4: "https://m.media-amazon.com/images/I/81pE+SeAS3L._SX466_.jpg",
            description: "Apple 2021 10.2-inch (25.91 cm) iPad with A13 Bionic chip (Wi-Fi + Cellular, 64GB) - Space Grey (9th Generation)",
            price: "41,499",
            rating: 4,
        },
    
        {
            id: 50,
            category: 'lablets',
            title: "Lenovo Tab M10 FHD Plus(3rd Gen)| 10.61 Inch, 2K Display",
            img1: "https://m.media-amazon.com/images/I/61yBf2b9dFL._SY450_.jpg",
            img2: "https://m.media-amazon.com/images/I/71m3q75paHL._SY450_.jpg",
            img3: "https://m.media-amazon.com/images/I/61MLGGvwE9L._SY450_.jpg",
            img4: "https://m.media-amazon.com/images/I/61ZU2U08t2L._SY450_.jpg",
            description: 'Lenovo Tab M10 FHD Plus(3rd Gen)| 10.61 Inch, 2K Display| 6 GB RAM, 128 GB ROM| Wi-Fi| Snapdragon Processor| 7700 mAH Battery| Quad Speakers with Dolby Atmos| TÜV Rheinland Low Blue Light Certified',
            price: "15,999",
            rating: 4,
        },
    
        {
            id: 49,
            category: 'lablets',
            title: "OnePlus Pad Go 28.85cm (11.35 inch) 2.4K 7:5 Ratio ReadFit Eye Care LCD Display,",
            img1: "https://m.media-amazon.com/images/I/51S19gkEn-L._SX425_.jpg",
            img2: "https://m.media-amazon.com/images/I/711O4zyemcL._SX425_.jpg",
            img3: "https://m.media-amazon.com/images/I/51S19gkEn-L._SX425_.jpg",
            img4: "https://m.media-amazon.com/images/I/41jTOS3CX2L._SX425_.jpg",
            description: "OnePlus Pad Go 28.85cm (11.35 inch) 2.4K 7:5 Ratio ReadFit Eye Care LCD Display, Dolby Atmos Quad Speakers,4G LTE(Calling) + Wi-Fi Connectivity Tablet, 8GB RAM 256 GB Storage Expandable Up-to 1TB",
            price: "23,999",
            rating: 4,
        },
    
        {
            id: 48,
            category: 'lablets',
            title: "HONOR Pad X8 with Free Flip-Cover, 25.65cm",
            img1: "https://m.media-amazon.com/images/I/31C8xR5JqWL._SX300_SY300_QL70_FMwebp_.jpg",
            img2: "https://m.media-amazon.com/images/I/71sAa-+jtOL._SY355_.jpg",
            img3: "https://m.media-amazon.com/images/I/81CIXBBTmUL._SY355_.jpg",
            img4: "https://m.media-amazon.com/images/I/71JSj3kgc7L._SY355_.jpg",
            description: 'HONOR Pad X8 with Free Flip-Cover, 25.65cm (10.1 inch) FHD Display, 4GB RAM 64GB ROM, Mediatek MT8786, Android 12, TUV Rheinland Certified Eye Protection, Up to 14 Hours Battery WiFi Tablet, Blue Hour',
            price: "11,999",
            rating: 4,
        },
    
      
    
    
    
    
    //   new 
     
    // mobile
    
    {
        id: 15,
        category: 'mobile',
        title: "Apple iPhone 11",
        img1: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
        img2: "https://m.media-amazon.com/images/I/71E9eFzWpEL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/813kKsQSclL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/81A4mZpvWBL._SX522_.jpg",
        amazonLink: 'https://amzn.to/44MiYi6',
        description: 'Apple iPhone 11 (64GB) - White',
        price: '79,999',
        rating: 4,
      },
    
    
      {
        id: 16,
        category: 'mobile',
        title: "Apple iPhone 14",
        img1: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        img2: 'https://rukminim2.flixcart.com/image/416/416/xif0q/monitor/l/8/z/-original-imagtthycycfrpnf.jpeg?q=70&crop=false',
        img3: 'https://m.media-amazon.com/images/I/711JE+dD1KL._SX522_.jpg',
        img4: 'https://m.media-amazon.com/images/I/61UR88veVzL._SX522_.jpg',
        amazonLink: 'https://amzn.to/3PuckZp',
        description: 'Apple iPhone 14 (128 GB) - Blue',
        price: '89,999',
        rating: 4,
      },
    
      {
        id: 17,
        category: 'mobile',
        title: "Apple iPhone 13",
        img1: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
        img2: "https://m.media-amazon.com/images/I/61CAYVr34QL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/81junVbiuyL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/71G44HUh7yL._SX522_.jpg",
        amazonLink: 'https://amzn.to/3r6XJtv',
        description: 'Apple iPhone 13 (128GB) - Blue',
        price: '69,999',
        rating: 4,
      },
    
      {
        id: 18,
        category: "mobile",
        title: 'IQOO Z9 5G (Brushed Green, 8GB RAM, 128GB Storage)',
        img1: 'https://m.media-amazon.com/images/I/61pt59LW-lL._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/617B0PQejiL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/61LLaU2mdRL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/616v0FlxYGL._SX569_.jpg',
        description: 'IQOO Z9 5G (Brushed Green, 8GB RAM, 128GB Storage) | Dimensity 7200 5G Processor | Sony IMX882 OIS Camera | 120Hz AMOLED with 1800 nits Local Peak Brightness | 44W Charger in The Box',
        price: '19,999',
        rating: 5,
    
      },
      {
        id: 19,
        category: 'mobile',
        title: 'Lava Agni 2 5G',
        amazonLink: 'https://www.amazon.in/Lava-Viridian-Dimensity-Processor-Superfast/dp/B0C467KFNM?ref_=Oct_DLandingS_D_6dc8fcd5_0',
        img1: "https://m.media-amazon.com/images/I/61OBw+XUiuL._SX679_.jpg",
        img2: "https://m.media-amazon.com/images/I/61xaZ69s-2L._SX569_.jpg",
        img3: "https://m.media-amazon.com/images/I/51+90NyEM-L._SX569_.jpg",
        img4: "https://m.media-amazon.com/images/I/51RJIMiGqfL._SX569_.jpg",
        description: "Lava Agni 2 5G (Glass Viridian, 8GB RAM, 256GB Storage) | India's First Dimensity 7050 Processor | 120 Hz Curved Amoled Display | 13 5G Bands | Superfast 66W Charging | Clean Android",
        price: '17,999',
        rating: 4,
    
      },
    
      {
        id: 20,
        category: "mobile",
        title: 'iQOO Neo9 Pro 5G (Fiery Red, 8GB RAM, 256GB Storage)',
        img1: 'https://m.media-amazon.com/images/I/718jcIFYaAL._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/71Qvj-ww7IL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/71jyObbkvpL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/61ilsCzs3RL._SX569_.jpg',
        description: 'iQOO Neo9 Pro 5G (Fiery Red, 8GB RAM, 256GB Storage) | Snapdragon 8 Gen 2 Processor | Supercomputing Chip Q1 | Flagship Level Sony IMX920 Camera',
        price: '37,999',
        rating: 3,
    
      },
    
      {
        id: 21,
        category: "mobile",
        title: 'Redmi 13C (Stardust Black, 4GB RAM, 128GB Storage) ',
        img1: 'https://m.media-amazon.com/images/I/71d1ytcCntL._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/61lqqQxR7VL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/81swpQdAPtL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/71FKAcHFrzL._SX569_.jpg',
        description: 'Redmi 13C (Stardust Black, 4GB RAM, 128GB Storage) | Powered by 4G Mediatek Helio G85 | 90Hz Display | 50MP AI Triple Camera',
        price: '7,799',
        rating: 4,
    
      },
    
      {
        id: 22,
        category: "mobile",
        title: 'iQOO Z7 Pro 5G (Blue Lagoon, 8GB RAM, 256GB Storage) | 3D Curved AMOLED Display',
        img1: 'https://m.media-amazon.com/images/I/61Id6WJDWqL._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/61fd1yUJ6kL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/71MUvQYhSOL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/71tyRMAtVrL._SX569_.jpg',
        description: "iQOO Z7 Pro 5G (Blue Lagoon, 8GB RAM, 256GB Storage) | 3D Curved AMOLED Display | 4nm MediaTek Dimesity 7200 5G Processor | 64MP Aura Light OIS Camera | Segment's Slimmest & Lightest Smartphone",
        price: '24,999',
        rating: 4,
    
      },
    
      {
        id: 23,
        category: "mobile",
        title: 'realme narzo 60X 5G（Stellar Green,6GB,128GB Storage ） ',
        img1: 'https://m.media-amazon.com/images/I/41tSQSq1xJL._SX300_SY300_QL70_FMwebp_.jpg',
        img2: 'https://m.media-amazon.com/images/I/81yNIhv3kLL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/81+HEx+yuIL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/719ftrLGjTL._SX569_.jpg',
        description: 'realme narzo 60X 5G（Stellar Green,6GB,128GB Storage ） Up to 2TB External Memory | 50 MP AI Primary Camera | Segments only 33W Supervooc Charge',
        price: '12,499',
        rating: 4,
    
      },
    
      {
        id:24 ,
        category: "mobile",
        title: 'iQOO 12 5G (Legend, 12GB RAM, 256GB Storage) ',
        img1: 'https://m.media-amazon.com/images/I/411gvmvNQzL._SX300_SY300_QL70_FMwebp_.jpg',
        img2: 'https://m.media-amazon.com/images/I/71P0B0AkteL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/71P0B0AkteL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/51RRloSx48L._SX569_.jpg',
        description: "iQOO 12 5G (Legend, 12GB RAM, 256GB Storage) | India's 1st Snapdragon® 8 Gen 3 Mobile Platform | India's only Flagship with 50MP + 50MP + 64MP Camera",
        price: '52,999',
        rating: 4,
    
      },
    
      {
        id: 25,
        category: "mobile",
        title: 'realme narzo 60 5G (Mars Orange,8GB+128GB) 90Hz Super AMOLED Display',
        img1: 'https://m.media-amazon.com/images/I/41snmTn9mrL._SX300_SY300_QL70_FMwebp_.jpg',
        img2: 'https://m.media-amazon.com/images/I/91i6C64GLSL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/91i6C64GLSL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/51tqBZdk0LL._SX569_.jpg',
        description: 'realme narzo 60 5G (Mars Orange,8GB+128GB) 90Hz Super AMOLED Display | Ultra Premium Vegan Leather Design | with 33W SUPERVOOC Charger',
        price: '14,999',
        rating: 4,
    
      },
    
      {
        id: 26,
        category: "mobile",
        title: 'Redmi 12 5G Moonstone Silver 4GB RAM 128GB ROM',
        img1: 'https://m.media-amazon.com/images/I/61SmnheBBRL._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/81tUOEJ5qGL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/812b5rqTYFL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/81SocKy8ghL._SX569_.jpg',
        description: 'Redmi 12 5G Moonstone Silver 4GB RAM 128GB ROM',
        price: '11,999',
        rating: 4,
    
      },
    
      {
        id: 27,
        category: "mobile",
        title: 'POCO M6 Pro 5G (Forest Green, 4GB RAM, 128GB Storage)',
        img1: 'https://m.media-amazon.com/images/I/41888-BWxKL._SX300_SY300_QL70_FMwebp_.jpg',
        img2: 'https://m.media-amazon.com/images/I/71PSpsrmXiL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/31+2EYAFRvL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/41YOC8PJKLL._SX569_.jpg',
        description: 'POCO M6 Pro 5G (Forest Green, 4GB RAM, 128GB Storage)',
        price: '10,499',
        rating: 4,
    
      },
    
      {
        id: 28,
        category: "mobile",
        title: 'HONOR X9b 5G (Midnight Black, 8GB + 256GB) ',
        img1: 'https://m.media-amazon.com/images/I/71H5JOOMacL._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/716RJpNcb7L._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/71xpdBV7eGL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/81dJIGBjYlL._SX569_.jpg',
        description: "HONOR X9b 5G (Midnight Black, 8GB + 256GB) | India's First Ultra-Bounce Anti-Drop Curved AMOLED Display | 5800mAh Battery | 108MP Primary Camera | Without Charger",
        price: '25,999',
        rating: 4,
    
      },
    
      {
        id: 29,
        category: "mobile",
        title: 'Apple iPhone 13 (128GB) - Midnight',
        img1: 'https://m.media-amazon.com/images/I/31tyUh1todL._SY445_SX342_QL70_FMwebp_.jpg',
        img2: 'https://m.media-amazon.com/images/I/61cecOpZrxL._SX522_.jpg',
        img3: 'https://m.media-amazon.com/images/I/71SfvBP1gBL._SX522_.jpg',
        img4: 'https://m.media-amazon.com/images/I/71G44HUh7yL._SX522_.jpg',
        description: 'Apple iPhone 13 (128GB) - Midnight',
        price: '52,499',
        rating: 4,
    
      },
    
      {
        id: 30,
        category: "mobile",
        title: 'realme narzo 60X 5G（Stellar Green,6GB,128GB Storage ）',
        img1: 'https://m.media-amazon.com/images/I/81WimZLWH1L._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/81yNIhv3kLL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/719ftrLGjTL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/61FhI6wTubL._SX569_.jpg',
        description: 'realme narzo 60X 5G（Stellar Green,6GB,128GB Storage ） Up to 2TB External Memory | 50 MP AI Primary Camera | Segments only 33W Supervooc Charge',
        price: '12,499',
        rating: 4,
    
      },
    
      {
        id: 31,
        category: "mobile",
        title: 'Redmi 12 5G Moonstone Silver 6GB RAM 128GB ROM',
        img1: 'https://m.media-amazon.com/images/I/41-2m5Oyv5L._SX300_SY300_QL70_FMwebp_.jpg',
        img2: 'https://m.media-amazon.com/images/I/81tUOEJ5qGL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/812b5rqTYFL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/81SocKy8ghL._SX569_.jpg',
        description: 'Redmi 12 5G Moonstone Silver 6GB RAM 128GB ROM',
        price: '12,999',
        rating: 4,
    
      },
    
      {
        id: 32,
        category: "mobile",
        title: 'Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Gray, 12GB, 256GB Storage)',
        img1: 'https://m.media-amazon.com/images/I/81njZjDqc6L._SX569_.jpg',
        img2: 'https://m.media-amazon.com/images/I/71JLhofuYJL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/71ZdFihN4YL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/71xI+CuesJL._SX569_.jpg',
        description: 'Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Gray, 12GB, 256GB Storage)',
        price: '1,29,999',
        rating: 4,
    
      },
    
      {
        id: 33,
        category: "mobile",
        title: 'Samsung Galaxy M14 4G (Sapphire Blue,4GB,64GB)',
        img1: 'https://m.media-amazon.com/images/I/913EiorAS0L._SX466_.jpg',
        img2: 'https://m.media-amazon.com/images/I/612MXeSOgtL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/61tJaVIgmZL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/71kh0ud1oWL._SX569_.jpg',
        description: 'Samsung Galaxy M14 4G (Sapphire Blue,4GB,64GB) | 50MP Triple Cam | 5000mAh Battery | Snapdragon 680 Processor | 2 Gen. OS Upgrade & 4 Year Security Update | 8GB RAM with RAM Plus | Without Charger',
        price: '8,999',
        rating: 4,
    
      },
    
      {
        id: 34,
        category: "mobile",
        title: 'Samsung Galaxy M34 5G (Waterfall Blue,8GB,128GB)',
        img1: 'https://m.media-amazon.com/images/I/51JaSbauK3L._SX300_SY300_QL70_FMwebp_.jpg',
        img2: 'https://m.media-amazon.com/images/I/81G1lBaY9eL._SX569_.jpg',
        img3: 'https://m.media-amazon.com/images/I/81jA2esZOuL._SX569_.jpg',
        img4: 'https://m.media-amazon.com/images/I/71oeJ4sFUWL._SX569_.jpg',
        description: 'Samsung Galaxy M34 5G (Waterfall Blue,8GB,128GB)|120Hz sAMOLED Display|50MP Triple No Shake Cam|6000 mAh Battery|4 Gen OS Upgrade & 5 Year Security Update|16GB RAM with RAM+|Android 13|Without Charger',
        price: '17,999',
        rating: 4,
    
      },
    
    
    
    //   Ac 
     
      {
        id: 35,
        category: "ac",
        title: "Voltas 2 Ton AC",
        img1: "https://m.media-amazon.com/images/I/41e6oqY5-ZL._SX522_.jpg",
        img2: "https://m.media-amazon.com/images/I/61lNccBChGL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/71sU9paZSYL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/713bTQaam4L._SX522_.jpg",
        description: "Voltas 2 Ton 3 Star, Inverter Split AC(Copper, 4-in-1 Adjustable Mode, Anti-dust Filter, 2023 Model, 243V Vectra Elite, White)",
        price: '29,990',
        rating: 4,
       },
       {
        id: 36,
        category: "ac",
        title: "Blue Star 1.5 AC",
        img1: "https://m.media-amazon.com/images/I/61nF5ekaaPL._SX522_.jpg",
        img2: "https://m.media-amazon.com/images/I/71kJdA4df5L._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/71RHfdrWBqL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/71a4KEvohKL._SX522_.jpg",
        description: "Blue Star 1.5 Ton 5 Star Convertible 5 in 1 Cooling Inverter Split Air Conditioner (IC518YNU, White)",
        price: '49,990',
        rating: 4,
       },
       {
        id: 37,        
        category: "ac",
        title: "Godrej 1 Ton AC",
        img1: "https://m.media-amazon.com/images/I/41ImBPm1ZxL._SX522_.jpg",
        img2: "https://m.media-amazon.com/images/I/71xtAVamQxL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/61-6CtSBCwL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/719vQqdKGfL._SX522_.jpg",
        description: "Godrej 1 Ton 3 Star, 5-In-1 Convertible Cooling, Inverter Split AC (Copper, I-Sense Technology, 2023 Model, AC 1T EI 12TINV3R32-GWA Split, White)",
        price: '28,760',
        rating: 4,
       },
    
       {
        id: 38,
        category: "ac",
        title: "Voltas 1 Ton AC",
        img1: "https://m.media-amazon.com/images/I/51ayyOq4zeL._SX522_.jpg",
        img2: "https://m.media-amazon.com/images/I/71TjfhrDjtL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/71yJpLk0eVL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/717+qhE5ARL._SX522_.jpg",
        description: "Voltas 1 Ton 3 Star, Inverter Split AC(Copper, 4-in-1 Adjustable Mode, Anti-dust Filter, 2023 Model, 123V Vectra Elegant, White)",
        price: '28,960',
        rating: 4,
       },
    
       {
        id: 39,
        category: "ac",
        title: "Voltas 1.4 Ton AC",
        img1: "https://m.media-amazon.com/images/I/21DEQIbG+2L._SX342_SY445_.jpg",
        img2: "https://m.media-amazon.com/images/I/51U7mfQOtTL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/51RqKRXB-WL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/51TMMn3fJzL._SX522_.jpg",
        description: "Voltas 1.4 Ton 3 Star Inverter Split AC(Copper, Adjustable Cooling, Anti-dust Filter, 2023 Model, 173V Vectra Platina, White)",
        price: '30,960',
        rating: 4,
       },
       {
        id: 40,
        category: "ac",
        title: "Voltas 1.5 Ton AC",
        img1: "https://m.media-amazon.com/images/I/41czO5UfdhL._SX522_.jpg",
        img2: "https://m.media-amazon.com/images/I/41ADIDB+8AL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/41+1FL5lsyL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/416NcU6au3L._SX522_.jpg",
        description: "Voltas 1.5 Ton 5 Star, Inverter Split AC(Copper, 4-in-1 Adjustable Mode, Anti-dust Filter, 2023 Model, 185V Vectra Elegant,White)",
        price: '28,990',
        rating: 4,
       },
    
       {
        id: 41,
        category: "ac",
        title: "Cruise 1 Ton AC",
        img1: "https://m.media-amazon.com/images/I/61bsv+IfsJL._SX522_.jpg",
        img2: "https://m.media-amazon.com/images/I/71zLZjch1ZL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/61bsv+IfsJL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/71Ggu-gTMsL._SX522_.jpg",
        description: "Cruise 1 Ton 3 Star Inverter Split AC with 7-Stage Air Filtration (100% Copper, Convertible 4-in-1, PM 2.5 Filter, 2024 Model, CWCVBH-VQ1W123, White)",
        price: '27,990',
        rating: 4,
       },
    
       {
        id: 42,
        category: "ac",
        title: "LG 1.5 Ton  AC",
        img1: "https://m.media-amazon.com/images/I/612bZ+umdzL._SX522_.jpg",
        img2: "https://m.media-amazon.com/images/I/719EOUWk1OL._SX522_.jpg",
        img3: "https://m.media-amazon.com/images/I/71-TLExSLQL._SX522_.jpg",
        img4: "https://m.media-amazon.com/images/I/71m9GJWhlAL._SX522_.jpg",
        description: "LG 1.5 Ton 5 Star DUAL Inverter Window AC (Copper, Convertible 4-in-1 cooling, RW-Q18WUZA, 2023 Model, HD Filter with Anti-Virus Protection, White)",
        price: '36,980',
        rating: 4,
       },
    
       {
        id: 43,
        category: "ac",
        title: "Carrier 1.5 Ton AC",
        img1: "https://m.media-amazon.com/images/I/51sTXvsanQL._SX466_.jpg",
        img2: "https://m.media-amazon.com/images/I/81r-A5yYwTL._SX466_.jpg",
        img3: "https://m.media-amazon.com/images/I/81Ypvsg7OTL._SX466_.jpg",
        img4: "https://m.media-amazon.com/images/I/71t-T-oqK0L._SX466_.jpg",
        description: "Carrier 1.5 Ton 3 Star AI Flexicool Inverter Split AC (Copper, Convertible 4-in-1 Cooling,High Density Filter, Auto Cleanser, 2023 Model,ESTER Exi - CAI18ER3R32F0,White)",
        price: '35,990',
        rating: 4,
       },
    
       {
        id: 44,
        category: "ac",
        title: "Daikin 1 Ton AC",
        img1: "https://m.media-amazon.com/images/I/41SygI1IVjL._SX466_.jpg",
        img2: "https://m.media-amazon.com/images/I/71Sx-3sMh6L._SX466_.jpg",
        img3: "https://m.media-amazon.com/images/I/71JBBYNdsiL._SX466_.jpg",
        img4: "https://m.media-amazon.com/images/I/61qTDdM19zL._SX466_.jpg",
        description: "Daikin 1 Ton 5 Star Inverter Split AC (Copper, PM 2.5 Filter, 2022 Model, MTKM35U, White)",
        price: '39,990',
        rating: 4,
       },
    
       {
        id: 45,
        category: "ac",
        title: "Lloyd 1.0 Ton AC",
        img1: "https://m.media-amazon.com/images/I/314HZjxgjUL._SX679_.jpg",
        img2: "https://m.media-amazon.com/images/I/61wBV8KhiFL._SX342_.jpg",
        img3: "https://m.media-amazon.com/images/I/61y51Mxr5wL._SX342_.jpg",
        img4: "https://m.media-amazon.com/images/I/71hg-QvvypL._SX342_.jpg",
        description: "Lloyd 1.0 Ton 3 Star Inverter Split AC (5 in 1 Convertible, Copper, Anti-Viral + PM 2.5 Filter, 2023 Model, White with Chrome Deco Strip, GLS12I3FWAEV/WAEA)",
        price: '29,990',
        rating: 4,
       },
    
       {
        id: 46,
        category: "ac",
        title: "Daikin 1.5 Ton AC",
        img1: "https://m.media-amazon.com/images/I/416pXec648L._SX466_.jpg",
        img2: "https://m.media-amazon.com/images/I/512D-mZndhL._SX466_.jpg",
        img3: "https://m.media-amazon.com/images/I/81GsnGncCnL._SX466_.jpg",
        img4: "https://m.media-amazon.com/images/I/61Gg9u35MML._SX466_.jpg",
        description: "Daikin 1.5 Ton 3 Star Inverter Split AC (Copper, PM 2.5 Filter, Triple Display, Dew Clean Technology, Coanda Airflow, 2023 Model, MTKL50U, White)",
        price: '36,990',
        rating: 5,
       },
    
       {
        id: 47,
        category: "ac",
        title: "Blue Star 0.8 Ton AC",
        img1: "https://m.media-amazon.com/images/I/51k0NvUmYLL._SX679_.jpg",
        img2: "https://m.media-amazon.com/images/I/81XIHDuDG5L._SX466_.jpg",
        img3: "https://m.media-amazon.com/images/I/41rgpetXysL._SX679_.jpg",
        img4: "https://m.media-amazon.com/images/I/41p9cBYft4L._SX679_.jpg",
        description: "Blue Star 0.8 Ton 3 Star Inverter Split Ac (Copper, Turbo Cool, Gold Fins, Comfort Sleep, Self Clean Technology, Multi Sensors, Eco Mode, Hidden Display, Stabiliser Free, 2023 Model,Ic309Rbtu,White)",
        price: '27,990',
        rating: 5,
       },
    







       {
        id: 51,
        category: "boat",
        title: "boAt Airdopes 141 Bluetooth TWS Earbuds with 42H",
        img1: "https://m.media-amazon.com/images/I/61KNJav3S9L._SX425_.jpg",
        img2: "https://m.media-amazon.com/images/I/61mEqp7RZXL._SX425_.jpg",
        img3: "https://m.media-amazon.com/images/I/71LIlNW980L._SX425_.jpg",
        img4: "https://m.media-amazon.com/images/I/61vBE3t4x1L._SX425_.jpg",
        description: "boAt Airdopes 141 Bluetooth TWS Earbuds with 42H Playtime,Low Latency Mode for Gaming, ENx Tech, IWP, IPX4 Water Resistance, Smooth Touch Controls(Bold Black)",
        price: '1,990',
        rating: 4,
       },
    
       {
        id: 52,
        category: "boat",
        title: "boAt Immortal 121 TWS",
        img1: "https://m.media-amazon.com/images/I/41w2pkIRKxL._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/61y3NPa0SUL._SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/81C4li-v9qL._SY355_.jpg",
        img4: "https://m.media-amazon.com/images/I/61glRpWr99L._SY355_.jpg",
        description: "boAt Immortal 121 TWS Earbuds with Beast™ Mode(40ms Low Latency) for Gaming, 40H Playtime, Blazing LEDs, Quad Mics ENx Signature Sound, ASAP™ Charge(10 Mins= 180 Mins)(Black Sabre)",
        price: '1,090',
        rating: 4,
       },
      
       {
        id: 53,
        category: "boat",
        title: "boAt Stone 650 10W",
        img1: "https://m.media-amazon.com/images/I/413SrzZZa2L._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/7188mVMrlRL._SX425_.jpg",
        img3: "https://m.media-amazon.com/images/I/71-cTEbUiRL._SX425_.jpg",
        img4: "https://m.media-amazon.com/images/I/71qErorOlLL._SX425_.jpg",
        description: "boAt Stone 650 10W Bluetooth Speaker with Upto 7 Hours Playback, IPX5 and Integrated Controls (Black)",
        price: '1,499',
        rating: 4,
       },
    
       {
        id: 54,
        category: "boat",
        title: "boAt Airdopes 141 ANC TWS in Ear",
        img1: "https://m.media-amazon.com/images/I/41lZmV-2+xL._SY300_SX300_.jpg",
        img2: "https://m.media-amazon.com/images/I/616bFiUe4LL._SX425_.jpg",
        img3: "https://m.media-amazon.com/images/I/61XrMPM8B-L._SX425_.jpg",
        img4: "https://m.media-amazon.com/images/I/61EM9e6YCFL._SX425_.jpg",
        description: "boAt Airdopes 141 ANC TWS in Ear Earbuds with 32 Db ANC, 42 Hrs Playback, 50Ms Low Latency Beast Mode, Iwp Tech,Quad Mics with Enx,ASAP Charge,USB Type-C Port & Ipx5(Gunmetal Black)",
        price: '1,490',
        rating: 4,
       },
    
       {
        id: 55,
        category: "boat",
        title: "boAt Rockerz 255 Pro+",
        img1: "https://m.media-amazon.com/images/I/31HCup1pqFL._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/61M8Vck-ZoL._SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/61Zv+5yK4CL._SY355_.jpg",
        img4: "https://m.media-amazon.com/images/I/91cLjEyJfcL._SY355_.jpg",
        description: "boAt Rockerz 255 Pro+ Bluetooth in Ear Neckband with Upto 60 Hours Playback, ASAP Charge, IPX7, Dual Pairing and Bluetooth v5.2(Active Black)",
        price: '999',
        rating: 4,
       },
    
       {
        id: 56,
        category: "boat",
        title: "boAt Airdopes 121v2 in-Ear True Wireless",
        img1: "https://m.media-amazon.com/images/I/31KjuRb9oNL._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/61o2urRxrcL._SX425_.jpg",
        img3: "https://m.media-amazon.com/images/I/61j3VLyxkHL._SX425_.jpg",
        img4: "https://m.media-amazon.com/images/I/61krTrhiVkL._SX425_.jpg",
        description: "boAt Airdopes 121v2 in-Ear True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight Earbuds & Multifunction Controls (Active Black, with Mic)",
        price: '990',
        rating: 4,
       },
    
       {
        id: 57,
        category: "boat",
        title: "boAt Airdopes 170 TWS Earbuds with",
        img1: "https://m.media-amazon.com/images/I/41Z0mNiPeLL._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/613pHIQdhEL._SX425_.jpg",
        img3: "https://m.media-amazon.com/images/I/613pHIQdhEL._SX425_.jpg",
        img4: "https://m.media-amazon.com/images/I/61c1puDLXxL._SX425_.jpg",
        description: "boAt Airdopes 170 TWS Earbuds with 50H Playtime, Quad Mics ENx™ Tech, Low Latency Mode, 13mm Drivers, ASAP™ Charge, IPX4, IWP™, Touch Controls & BT v5.3(Classic Black)",
        price: '1,990',
        rating: 4,
       },
    
       {
        id: 58,
        category: "boat",
        title: "boAt Rockerz 255 Pro+",
        img1: "https://m.media-amazon.com/images/I/31HCup1pqFL._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/61F-EnHAdFL._SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/61M8Vck-ZoL._SY355_.jpg",
        img4: "https://m.media-amazon.com/images/I/61Zv+5yK4CL._SY355_.jpg",
        description: "boAt Rockerz 255 Pro+ Bluetooth in Ear Neckband with Upto 60 Hours Playback, ASAP Charge, IPX7, Dual Pairing and Bluetooth v5.2(Active Black)",
        price: '999',
        rating: 4,
       },
    
       {
        id: 59,
        category: "boat",
        title: "boAt Airdopes Atom 81 TWS Earbuds with Upto 50H",
        img1: "https://m.media-amazon.com/images/I/41cU0ptdpWL._SX300_SY300_QL70_FMwebp_.jpg",
        img2: "https://m.media-amazon.com/images/I/61OOrL6oh6L._SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/61aaos19uXL._SY355_.jpg",
        img4: "https://m.media-amazon.com/images/I/61gAcTx3SbL._SY355_.jpg",
        description: "boAt Airdopes Atom 81 TWS Earbuds with Upto 50H Playtime, Quad Mics ENx™ Tech, 13MM Drivers,Super Low Latency(50ms), ASAP™ Charge, BT v5.3(Opal Black)",
        price: '29,990',
        rating: 4,
       },
       {
        id: 60,
        category: "boat",
        title: "boAt Airdopes 121 PRO TWS Earbuds",
        img1: "https://m.media-amazon.com/images/I/31+Jv5wLqoL._SY300_SX300_.jpg",
        img2: "https://m.media-amazon.com/images/I/613WUAMjUtL._SX425_.jpg",
        img3: "https://m.media-amazon.com/images/I/61acOoUimQL._SX425_.jpg",
        img4: "https://m.media-amazon.com/images/I/61xtXX0-HeL._SX425_.jpg",
        description: "boAt Airdopes 121 PRO TWS Earbuds Signature Sound, Quad Mic ENx™, Low Latency Mode for Gaming, 50H Playtime, IWP™, IPX4, Battery Indicator Screen(Active Black)",
        price: '890',
        rating: 4,
       },
    
    


{
    id: 101,
    category: "Shoes",
    title: "Red Tape Sports Walking Shoes for Men | Comfortable Slip-Resistant",
    img1: "https://m.media-amazon.com/images/I/71F8mgqczYL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/81IF9JO21IL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/61wvXOrJQlL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61-LRc0jsbL.SY500.jpg",
    description: "Red Tape Sports Walking Shoes for Men | Comfortable Slip-Resistant",
    price: '999',
    rating:4.5 ,
   },{
    id:102 ,
    category: "Shoes",
    title: "Red Tape Sports Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/61Eg-nqXjCL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/61uDtc4c7WL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/710u+nB3ADL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Sports Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '1,299',
    rating:4 ,
   },{
    id:103 ,
    category: "Shoes",
    title: "Red Tape Casual Sports Shoes for Men",
    img1: "https://m.media-amazon.com/images/I/61XtqC-cKcL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/61ohwa1wizL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/71Aze0COO3L.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Casual Sports Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '1,700',
    rating: 4,
   },{
    id:104 ,
    category: "Shoes",
    title: "Red Tape Casual Sneaker Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/61pP0T29jNL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/716gdJcrEgL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/617-bbaTpbL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Casual Sneaker Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '1,500',
    rating: 4.5,
   },{
    id: 105 ,
    category: "Shoes",
    title: "Red Tape Sports Athleisure Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/619KWm93lsL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/61zIGhymkIL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/715+3UcX45L.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Sports Athleisure Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '1,200',
    rating:3.5 ,
   },{
    id: 106,
    category: "Shoes",
    title: "Red Tape Sports Walking Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/61LcfBzBpyL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/81vAhp2q9DL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/61dQ8Gm72pL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61-LRc0jsbL.SY500.jpg",
    description: "Red Tape Sports Walking Shoes for Men | Slip Resistant & Comfortable",
    price: '900',
    rating: 3,
   },{
    id: 107,
    category: "Shoes",
    title: "Red Tape Men's Sneakers",
    img1: "https://m.media-amazon.com/images/I/51-TW9wAZWL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/810E-cp91tL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/613Xz882RPL.SY500.jpg",
    description: "Red Tape Men's Sneakers",
    price: '1,000',
    rating: 4 ,
   },{
    id: 108,
    category: "Shoes",
    title: "Red Tape Casual Vulcanised Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/51otKbq+BXL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/51Vc+gJH8-L.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/71mS4twSXGL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Casual Vulcanised Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '900',
    rating: 3.5,
   },{
    id: 109,
    category: "Shoes",
    title: "Red Tape Sneaker Casual Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/61X65gXY1sL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/710sXgNmE4L.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/61n8vXThUYL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61-LRc0jsbL.SY500.jpg",
    description: "Red Tape Sneaker Casual Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '1,300',
    rating:4 ,
   },{
    id: 110,
    category: "Shoes",
    title: "Red Tape Casual Sneaker Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/61bNZw913mL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/81OQxh-k1EL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/61CSrq8ZsdL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Casual Sneaker Shoes for Men | Cultured Round-Toe Shape, Extremely Soft & Impact Relief",
    price: '1,200',
    rating: 5,
   },{
    id: 111,
    category: "Shoes",
    title: "Red Tape Sneaker Casual Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/61rotozjC0L.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/81OoP6TQtHL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/61zZYf7lwgL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Sneaker Casual Shoes for Men | Soft Cushion Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Perfect for Casual Wear",
    price: '1,199',
    rating: 4,
   },{
    id: 112,
    category: "Shoes",
    title: "Red Tape White/Blue Vulcanised Casual Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/51LL+IJ6HxL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/81ekajIh57L.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/61oMsTD4HUL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape White/Blue Vulcanised Casual Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '1,800',
    rating:4 ,
   },{
    id: 113,
    category: "Shoes",
    title: "Red Tape Casual Lifestyle Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/616As-HfFqL.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/61IvgRI4AYL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/71EZr3zF8zL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Casual Lifestyle Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '2,000',
    rating: 5,
   },{
    id: 114,
    category: "Shoes",
    title: "Red Tape Sneaker Casual Shoes for Men's ",
    img1: "https://m.media-amazon.com/images/I/616o37MmMxL.SY575.jpg",
    img2: "https://m.media-amazon.com/images/I/81TrDKfldWL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/71ofOTVt-vL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Sneaker Casual Shoes for Men's | Soft Cushion Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Perfect for Casual Wear",
    price: '900',
    rating:4 ,
   },{
    id: 115,
    category: "Shoes",
    title: "Red Tape Sports Walking Shoes for Men ",
    img1: "https://m.media-amazon.com/images/I/61lT1Q1VL+L.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/81jap8vn5oL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/71wknQ8BApL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61FhEGsNMXL.SY500.jpg",
    description: "Red Tape Sports Walking Shoes for Men | Soft Cushioned Insole, Slip-Resistance, Dynamic Feet Support, Arch Support & Shock Absorption",
    price: '3,000',
    rating:5 ,
   },



   // clothes
   {
    id:116 ,
    category: " clothes",
    title: "UNITED COLORS OF BENETTON Men's T-Shirt",
    img1: "https://m.media-amazon.com/images/I/61EJh8JsebL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61FwF3Uf20L.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61e9sTEY3bL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/511fN8k8ngL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men's T-Shirt",
    price: '507',
    rating: 4 ,
   },{
    id:117 ,
    category: " clothes",
    title: "United Colors of Benetton Men's Slim Shirt",
    img1: "https://m.media-amazon.com/images/I/711f2oEN0zL.SY550.jpg",
    img2: "https://m.media-amazon.com/images/I/715soD3Q7SL.SY550.jpg",
    img3: "https://m.media-amazon.com/images/I/71aDPWUroUL.SY550.jpg",
    img4: "https://m.media-amazon.com/images/I/71X+IKcIM2L.SY550.jpg",
    description: "United Colors of Benetton Men's Slim Shirt",
    price: '1,200',
    rating: 4,
   },{
    id: 118,
    category: " clothes",
    title: "UNITED COLORS OF BENETTON Men T-Shirt",
    img1: "https://m.media-amazon.com/images/I/617PTCcTwWL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61kPUzO3rNL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61-LtHSTBsL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/61xiaYHn+KL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men T-Shirt",
    price: '800',
    rating: 4,
   },{
    id:119 ,
    category: " clothes",
    title: "UNITED COLORS OF BENETTON Men's Slim T-Shirt",
    img1: "https://m.media-amazon.com/images/I/51-sibmqcpL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/51gmwj-OacL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/311v-5fXK+L.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51YHiobsTDL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men's Slim T-Shirt",
    price: '600',
    rating: 4 ,
   },{
    id:120,
    category: " clothes",
    title: "UNITED COLORS OF BENETTON Men's T-Shirt",
    img1: "https://m.media-amazon.com/images/I/71K+OfcbGBL.SY550.jpg",
    img2: "https://m.media-amazon.com/images/I/71-+m-ggkHL.SY550.jpg",
    img3: "https://m.media-amazon.com/images/I/711Lbm-73OL.SY550.jpg",
    img4: "https://m.media-amazon.com/images/I/91YtGJCC1OL.SY550.jpg",
    description: "UNITED COLORS OF BENETTON Men's T-Shirt",
    price: '500',
    rating: 4 ,
   },{
    id:121 ,
    category: " clothes",
    title: "UNITED COLORS OF BENETTON Men's T-Shirt",
    img1: "https://m.media-amazon.com/images/I/61stZNOqZGL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/519hpJrxCRL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61-C0L3777L.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51jc9WXJ7EL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men's T-Shirt",
    price: '500',
    rating: 4 ,
   },{
    id:122 ,
    category: " clothes",
    title: "UNITED COLORS OF BENETTON Men T-Shirt",
    img1: "https://m.media-amazon.com/images/I/613AFB+DoKL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61SMNNNKPaL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/71dwbtnYUGL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51dldELj88L.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men T-Shirt",
    price: '1,600',
    rating: 4 ,
   },{
    id:123 ,
    category: " clothes",
    title: "UNITED COLORS OF BENETTON Cotton Printed Spread Collar Mens Shirts",
    img1: "https://m.media-amazon.com/images/I/71ScWSjyuTL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/71eWhqMM07L.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/71z4eSaCTPL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/61sRBApKfoL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Cotton Printed Spread Collar Mens Shirts",
    price: '1,000',
    rating: 4 ,
   },
   {
    id:124 ,
    category: "clothes",
    title: "UNITED COLORS OF BENETTON Men's Polo Shirt",
    img1: "https://m.media-amazon.com/images/I/61pwXH3s45L.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61yMt6iA-sL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61+4Umb9hwL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51sZjqec4CL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men's Polo Shirt",
    price: '800',
    rating: 4 ,
   },{
    id:125 ,
    category: "clothes",
    title: "UNITED COLORS OF BENETTON Men's Regular Fit Spread Collar Solid Shirt",
    img1: "https://m.media-amazon.com/images/I/61R7pFYPobL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61LE8HQl0zL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/619JmlaCPEL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51BkGLkD-CL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men's Regular Fit Spread Collar Solid Shirt",
    price: '1,500',
    rating: 4,
   },{
    id:126 ,
    category: "clothes",
    title: "UNITED COLORS OF BENETTON Cotton Printed Round Neck Mens T-Shirts",
    img1: "https://m.media-amazon.com/images/I/617IrPLvVQL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61P7m5ABaZL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/51zJV3Sk5ML.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51RdpWF32JL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Cotton Printed Round Neck Mens T-Shirts",
    price: '500',
    rating: 4 ,
   },{
    id:127 ,
    category: "clothes",
    title: "UNITED COLORS OF BENETTON Men's T-Shirt",
    img1: "https://m.media-amazon.com/images/I/61UJRbwrcVL.SY550.jpg",
    img2: "https://m.media-amazon.com/images/I/61E9f62Dk9L.SY550.jpg",
    img3: "https://m.media-amazon.com/images/I/71WbKF4TSnL.SY550.jpg",
    img4: "https://m.media-amazon.com/images/I/618dKuarkXL.SY550.jpg",
    description: "UNITED COLORS OF BENETTON Men's T-Shirt",
    price: '600',
    rating: 4 ,
   },{
    id:128 ,
    category: "clothes",
    title: "UNITED COLORS OF BENETTON Men Shirt",
    img1: "https://m.media-amazon.com/images/I/61vI5eqwlpL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61cwSU1P7YL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61VjYezurVL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51hLEBDUtDL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men Shirt",
    price: '1,500',
    rating: 4 ,
   },{
    id:129 ,
    category: "clothes",
    title: "UNITED COLORS OF BENETTON Men T-Shirt",
    img1: "https://m.media-amazon.com/images/I/61wTZoBxKsL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61aBLXfOeTL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61uRcTP6BUL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/51DsQoem-nL.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men T-Shirt",
    price: '700',
    rating: 4 ,
   },{
    id:130 ,
    category: "clothes",
    title: "UNITED COLORS OF BENETTON Men's T-Shirt",
    img1: "https://m.media-amazon.com/images/I/61x9KEL-N7L.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/61Nhv1LY6dL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61Mai7cvA7L.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/512XA85QS9L.SX522.jpg",
    description: "UNITED COLORS OF BENETTON Men's T-Shirt",
    price: '600',
    rating: 4 ,
   },

   // Watches
   
   
   
   {
    id:131 ,
    category: "Watch",
    title: "Michael Kors Gen 6 Bradshaw Digital Black Dial Women's Watch-MKT5139",
    img1: "https://m.media-amazon.com/images/I/7189NAwmDNL.SL1500.jpg",
    img2: "https://m.media-amazon.com/images/I/71gRjWJ5EGL.SL1500.jpg",
    img3: "https://m.media-amazon.com/images/I/71gRjWJ5EGL.SL1500.jpg",
    img4: "https://m.media-amazon.com/images/I/71clokRI9gL.SL1500.jpg",
    description: "Michael Kors Gen 6 Bradshaw Digital Black Dial Women's Watch-MKT5139",
    price: '18,000',
    rating: 4 ,
   },{
    id:132 ,
    category: "Watch",
    title: "EA7 Emporio Armani Stainless Steel Chronograph Men's Watch",
    img1: "https://m.media-amazon.com/images/I/41cz+fpPqtL.SX425.jpg",
    img2: "https://m.media-amazon.com/images/I/41Ie8b9r2zL.SX425.jpg",
    img3: "https://m.media-amazon.com/images/I/419oqxawvpL.SX425.jpg",
    img4: "https://m.media-amazon.com/images/I/41BPaknEcWL.SX425.jpg",
    description: "EA7 Emporio Armani Stainless Steel Chronograph Men's Watch",
    price: '18,000',
    rating: 4,
   },{
    id:133 ,
    category: "Watch",
    title: "NIBOSI Men's Watches Analog Business Chronograph Casual Watches Military Waterproof Stainless Steel Wrist Watches for Boy",
    img1: "https://m.media-amazon.com/images/I/71x2rHMaN+L.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/71PgKdixlaL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/51fP6CkO7qL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/71vtFWnegEL.SX522.jpg",
    description: "NIBOSI Men's Watches Analog Business Chronograph Casual Watches Military Waterproof Stainless Steel Wrist Watches for Boy",
    price: '4,000',
    rating: 4,
   },{
    id:134 ,
    category: "Watch",
    title: "NIBOSI Men Watches Analog Quartz Stainless Steel Military Watches for Men Waterproof Business Classic Desiger Wrist Watch Date",
    img1: "https://m.media-amazon.com/images/I/7132B2beZDL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/71F6izpbplL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/61xEo0wPBPL.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/71WyhKPf5nL.SX522.jpg",
    description: "NIBOSI Men Watches Analog Quartz Stainless Steel Military Watches for Men Waterproof Business Classic Desiger Wrist Watch Date",
    price: '3,000',
    rating: 4 ,
   },{
    id:135 ,
    category: "Watch",
    title: "beatXP Flare Pro 1.39” HD Display Bluetooth Calling Smart Watch, 100+ Sports Modes, Heart Rate Monitoring, SpO2, AI Voice Assistant, IP68 - Black",
    img1: "https://m.media-amazon.com/images/I/61MnrUAKACL.SL1500.jpg",
    img2: "https://m.media-amazon.com/images/I/71e3yepE0HL.SL1500.jpg",
    img3: "https://m.media-amazon.com/images/I/71JBYUhLOQL.SL1500.jpg",
    img4: "https://m.media-amazon.com/images/I/71Cqk28DJcL.SL1500.jpg",
    description: "beatXP Flare Pro 1.39” HD Display Bluetooth Calling Smart Watch, 100+ Sports Modes, Heart Rate Monitoring, SpO2, AI Voice Assistant, IP68 - Black",
    price: '1,000',
    rating: 4,
   },{
    id:136 ,
    category: "Watch",
    title: "Fire-Boltt Ninja Call Pro Plus 1.83",
    img1: "https://m.media-amazon.com/images/I/61AHiYyu3ZL.SL1500.jpg",
    img2: "https://m.media-amazon.com/images/I/81DEzbJ9ERL.SL1500.jpg",
    img3: "https://m.media-amazon.com/images/I/71tOBelnDYL.SL1500.jpg",
    img4: "https://m.media-amazon.com/images/I/61nWKX1mD0L.SL1500.jpg",
    description: 'Fire-Boltt Ninja Call Pro Plus 1.83" Smart Watch with Bluetooth Calling, AI Voice Assistance, 100 Sports Modes IP67 Rating, 240 * 280 Pixel High Resolution',
    price: '2,000',
    rating: 4 ,
   },{
    id:137 ,
    category: "Watch",
    title: "Noise Pulse Go Buzz Smart Watch with Advanced Bluetooth Calling",
    img1: "https://m.media-amazon.com/images/I/61wJNP17lEL.SL1500.jpg",
    img2: "https://m.media-amazon.com/images/I/61SvazFMS5L.SL1500.jpg",
    img3: "https://m.media-amazon.com/images/I/61C7QxrH7NL.SL1500.jpg",
    img4: "https://m.media-amazon.com/images/I/71xJDte4RJL.SL1500.jpg",
    description: 'Noise Pulse Go Buzz Smart Watch with Advanced Bluetooth Calling, 1.69" TFT Display, SpO2, 100 Sports Mode with Auto Detection, Upto 7 Days Battery (2 Days with Heavy Calling) - Rose Pink',
    price: '2,000',
    rating: 4 ,
   },{
    id:138 ,
    category: "Watch",
    title: "boAt Xtend Smart Watch with Alexa Built-in, 1.69” HD Display",
    img1: "https://m.media-amazon.com/images/I/61IMRs+o0iL.SL1500.jpg",
    img2: "https://m.media-amazon.com/images/I/91UJckBDRmL.SL1500.jpg",
    img3: "https://m.media-amazon.com/images/I/61xpcLbq06L.SL1500.jpg",
    img4: "https://m.media-amazon.com/images/I/61kiyOAUbKL.SL1500.jpg",
    description: "boAt Xtend Smart Watch with Alexa Built-in, 1.69” HD Display, Multiple Watch Faces, Stress Monitor, Heart & SpO2 Monitoring, 14 Sports Modes, Sleep Monitor, 5 ATM & 7 Days Battery(Pitch Black)",
    price: '1,000',
    rating: 4 ,
   },{
    id:139 ,
    category: "Watch",
    title: "Matrix Antique 2.0 Day & Date Softest Silicone Strap Analog Watch for Men & Boys",
    img1: "https://m.media-amazon.com/images/I/711NXCmUfbL.SX522.jpg",
    img2: "https://m.media-amazon.com/images/I/71B4dSrAPzL.SX522.jpg",
    img3: "https://m.media-amazon.com/images/I/71Dpouzxx+L.SX522.jpg",
    img4: "https://m.media-amazon.com/images/I/71Oejmvm6uL.SX522.jpg",
    description: "Matrix Antique 2.0 Day & Date Softest Silicone Strap Analog Watch for Men & Boys",
    price: '300',
    rating: 3 ,
   },{
    id: 140 ,
    category: "Watch",
    title: "Casio Vintage Digital Stainless Steel Grey Dial Silver Band Unisex Watch A-158WA-1Q ( D011 )",
    img1: "https://m.media-amazon.com/images/I/61ybeKQto8L.SY500.jpg",
    img2: "https://m.media-amazon.com/images/I/51MqeOhdLXL.SY500.jpg",
    img3: "https://m.media-amazon.com/images/I/51gzzWA5ToL.SY500.jpg",
    img4: "https://m.media-amazon.com/images/I/61MWAunga8L.SY500.jpg",
    description: "Casio Vintage Digital Stainless Steel Grey Dial Silver Band Unisex Watch A-158WA-1Q ( D011 )",
    price: '2,000',
    rating: 4 ,
   },]